services:
  postgres:
    image: postgres:16
    container_name: ai-qfome_postgres
    restart: always
    environment:
      POSTGRES_DB: ai-qfome_db
      POSTGRES_USER: ai-qfome_user
      POSTGRES_PASSWORD: ai-qfome_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ai-qfome

  redis:
    image: redis:alpine
    container_name: ai-qfome_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ai-qfome
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_ai-qfome
    volumes:
      - .:/app
    environment:
      - APP_NAME=AI-QFome
      - APP_ENV=local
      - APP_KEY=base64:pyscnm8nXHJ0rddXxazQ/217WuB1wPBHov0n/ozwLpw=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8030

      # Locale
      - APP_LOCALE=en
      - APP_FALLBACK_LOCALE=en
      - APP_FAKER_LOCALE=en_US

      # Log
      - LOG_CHANNEL=stack
      - LOG_STACK=single
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug

      # Banco de Dados (PostgreSQL no serviço 'postgres')
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=ai-qfome_db
      - DB_USERNAME=ai-qfome_user
      - DB_PASSWORD=ai-qfome_pass

      # Cache / Sessão / Fila (Redis no serviço 'redis')
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - QUEUE_CONNECTION=redis

      - REDIS_CLIENT=phpredis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

      # Broadcast / Filesystem
      - BROADCAST_CONNECTION=log
      - FILESYSTEM_DISK=local

      # E-mail
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=no-reply@ai-qfome.local
      - MAIL_FROM_NAME="${APP_NAME}"

      # Octane (Swoole)
      - OCTANE_SERVER=swoole
      - OCTANE_HTTPS=false
    depends_on:
      - postgres
      - redis
    networks:
      - ai-qfome
    command: >-
      sh -lc '
        php artisan optimize:clear &&
        php artisan optimize &&
        if [ ! -f vendor/laravel/octane/composer.json ]; then composer require laravel/octane:^2.0 --no-interaction || true; fi &&
        if [ ! -f config/octane.php ]; then php artisan octane:install --server=swoole -n || true; fi &&
        php artisan migrate --force &&
        php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000
      '

  nginx:
    image: nginx:alpine
    container_name: ai-qfome_nginx
    depends_on:
      - app
    ports:
      - "8030:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - .:/app:ro
    networks:
      - ai-qfome

volumes:
  postgres-data:
  redis-data:

networks:
  ai-qfome:
    # external: true
    driver: bridge